language: go

go:
  - 1.9.x

branches:
  only:
    - master

before_install:
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get -y update
  - sudo apt-get -y install solc

script:
  - go test -v ./...
